DATA RATE;
INFILE "D:\Academie\6271\A2\Weekly_interest.txt";
INPUT FF TB03 CM10 PRIME AAA;

TIME=_N_;
FFDIF=DIF(FF);
TB03DIF=DIF(TB03);
CM10DIF=DIF(CM10);
PRIMEDIF=DIF(PRIME);
AAADIF=DIF(AAA);

PROC REG;
MODEL AAADIF=CM10DIF;
OUTPUT OUT=ACRe P=ACPre PM=ACPM;
RUN;

PROC GPLOT;
PLOT AAADIF*CM10DIF=1 ACPM*TIME=2;
SYMBOL1 I=NONE V=PLUS;
RUN;
