data NIKKEI;
infile "D:\Academie\6271\A7\NIKKEI.TXT";
input NIKKEI;
TIME=_N_;

NIKKEIDIFF=DIF(NIKKEI);
NIKKEILAG=LAG(NIKKEI);

PROC REG;
MODEL NIKKEIDIFF=TIME NIKKEILAG;

PROC ARIMA;
IDENTIFY VAR=NIKKEI STATIONARITY=(DICKEY=0);

RUN;
